apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        run: busybox  
    name: busybox  
    namespace: web
spec:
    containers:
    - args:
        - /bin/sh
        - -c    
        - sleep 3600   
      image: busybox    
      name: busybox
      resources: {}
      volumeMounts:
        - name: temp-data      
          mountPath: /tmp/data  \
    volumes:
    - name: temp-data
      persistentVolumeClaim:
        claimName: data-pvc
    dnsPolicy: ClusterFirst
    restartPolicy: Never
status: {}