apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: data-pvc
        namespace: web
spec:
        resources:
                requests:
                        storage: 256Mi
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage